#!/bin/bash

#echo $(node test.js)
VAR="cat $(node test.js)"
if [ "$VAR" == "true" ];
then 
	echo "recyclable"
	#$(gcc -o green green.c)
	#$(./green.c)
else
	echo "not recyclable"
	#$(gcc -o red red.c)
        #$(./red.c)

fi
