#!/bin/bash

#echo $(node test.js)
VAR="cat $(node test.js)"
if [ "$VAR" == "true" ];
then 
	echo "yayyyy"
	$(gcc -o green green.c)
	$(./green.c)
else
	echo "noooo"
	$(gcc -o red red.c)
        $(./red.c)

fi
